server:
  port: 9005
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/MrAldhair/spring-cloud-config-curso
          search-paths: config-data
  application:
    name: server-config